<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\LostPolygon.AspNetCore.Utility.Web\LostPolygon.AspNetCore.Utility.Web.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BlazorStrap" Version="5.2.103" />
      <PackageReference Include="BlazorStrap.V4" Version="5.2.103" />
    </ItemGroup>

</Project>
